/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpcolecciones;

import java.awt.Component;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.JPanel;

/**
 *
 * @author Martin
 */
public class FrDirectorioTelefonico extends javax.swing.JFrame {

    /**
     * Creates new form FrDirectorioTelefonico
     */
    public static final HashMap<Long,Cliente> clientes = new HashMap();
    public static final DirectorioTelefonico directorio = new DirectorioTelefonico();
    public FrDirectorioTelefonico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtFormDirectorio = new javax.swing.JLabel();
        buttAggClient = new javax.swing.JButton();
        buttBuscarClient = new javax.swing.JButton();
        buttBorrarClient = new javax.swing.JButton();
        buttSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAggCliente = new javax.swing.JMenuItem();
        miBuscarCliente = new javax.swing.JMenuItem();
        miBorrarCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        txtFormDirectorio.setBackground(new java.awt.Color(255, 0, 51));
        txtFormDirectorio.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtFormDirectorio.setForeground(new java.awt.Color(255, 255, 255));
        txtFormDirectorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFormDirectorio.setText("Directorio Telefonico");
        txtFormDirectorio.setToolTipText("");
        txtFormDirectorio.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        buttAggClient.setBackground(new java.awt.Color(0, 51, 51));
        buttAggClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttAggClient.setForeground(new java.awt.Color(255, 255, 255));
        buttAggClient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Downloads\\usuario (1).png")); // NOI18N
        buttAggClient.setText("Agregar Cliente/s");
        buttAggClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAggClientActionPerformed(evt);
            }
        });

        buttBuscarClient.setBackground(new java.awt.Color(0, 51, 51));
        buttBuscarClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttBuscarClient.setForeground(new java.awt.Color(255, 255, 255));
        buttBuscarClient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Downloads\\buscar.png")); // NOI18N
        buttBuscarClient.setText("Buscar Cliente/s");
        buttBuscarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttBuscarClientActionPerformed(evt);
            }
        });

        buttBorrarClient.setBackground(new java.awt.Color(0, 51, 51));
        buttBorrarClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttBorrarClient.setForeground(new java.awt.Color(255, 255, 255));
        buttBorrarClient.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Downloads\\remove-user.png")); // NOI18N
        buttBorrarClient.setText("Borrar Cliente/s");
        buttBorrarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttBorrarClientActionPerformed(evt);
            }
        });

        buttSalir.setBackground(new java.awt.Color(0, 51, 51));
        buttSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttSalir.setForeground(new java.awt.Color(255, 255, 255));
        buttSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Downloads\\salida-de-emergencia.png")); // NOI18N
        buttSalir.setText("Salir");
        buttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSalirActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin\\Downloads\\letra-c (1).png")); // NOI18N
        jLabel1.setText("2022-2022 Grupo 6 - All rights reserved");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttAggClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttBuscarClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttBorrarClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFormDirectorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(buttSalir)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtFormDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttAggClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttBuscarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttBorrarClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        miAggCliente.setText("Agregar Cliente");
        miAggCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAggClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miAggCliente);

        miBuscarCliente.setText("Buscar Cliente");
        miBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miBuscarCliente);

        miBorrarCliente.setText("Borrar Cliente");
        miBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miBorrarCliente);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttAggClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAggClientActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_AggCliente friAggCliente = new Fri_AggCliente();
        friAggCliente.setVisible(true);
        jDesktopPane1.add(friAggCliente);
    }//GEN-LAST:event_buttAggClientActionPerformed

    private void buttBuscarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttBuscarClientActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_BuscarCliente friBuscarCliente = new Fri_BuscarCliente();
        friBuscarCliente.setVisible(true);
        jDesktopPane1.add(friBuscarCliente);
    }//GEN-LAST:event_buttBuscarClientActionPerformed

    private void buttBorrarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttBorrarClientActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_BorrarCliente friBorrarCliente = new Fri_BorrarCliente();
        friBorrarCliente.setVisible(true);
        jDesktopPane1.add(friBorrarCliente);
    }//GEN-LAST:event_buttBorrarClientActionPerformed

    private void buttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttSalirActionPerformed

    private void miAggClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAggClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_AggCliente friAggCliente = new Fri_AggCliente();
        friAggCliente.setVisible(true);
        jDesktopPane1.add(friAggCliente);
    }//GEN-LAST:event_miAggClienteActionPerformed

    private void miBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_BuscarCliente friBuscarCliente = new Fri_BuscarCliente();
        friBuscarCliente.setVisible(true);
        jDesktopPane1.add(friBuscarCliente);
    }//GEN-LAST:event_miBuscarClienteActionPerformed

    private void miBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarClienteActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Fri_BorrarCliente friBorrarCliente = new Fri_BorrarCliente();
        friBorrarCliente.setVisible(true);
        jDesktopPane1.add(friBorrarCliente);
    }//GEN-LAST:event_miBorrarClienteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrDirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrDirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrDirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrDirectorioTelefonico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrDirectorioTelefonico().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttAggClient;
    private javax.swing.JButton buttBorrarClient;
    private javax.swing.JButton buttBuscarClient;
    private javax.swing.JButton buttSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAggCliente;
    private javax.swing.JMenuItem miBorrarCliente;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JLabel txtFormDirectorio;
    // End of variables declaration//GEN-END:variables
}
